import type {Metadata} from "next";
// import {Inter,Gothic_A1} from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "@/libs/registry/styledComponentsRegistry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
